import { Svgs } from '../constants';

export default [
  'headerSelect',
  'blockquote',
  '|',
  'bold',
  'underline',
  'italic',
  {
    key: 'group-more-style',
    title: '更多',
    iconSvg: Svgs.MORE,
    menuKeys: ['through', 'code', 'sup', 'sub', 'clearStyle'],
  },
  'color',
  'bgColor',
  '|',
  'fontSize',
  'fontFamily',
  'lineHeight',
  '|',
  'bulletedList',
  'numberedList',
  'todo',
  {
    key: 'group-aligns',
    title: '对齐方式',
    iconSvg: Svgs.ALIGNS,
    menuKeys: [
      'justifyLeft',
      'justifyCenter',
      'justifyRight',
      'justifyJustify',
    ],
  },
  {
    key: 'group-indent',
    title: '缩进方式',
    iconSvg: Svgs.INDENT,
    menuKeys: ['indent', 'delIndent'],
  },
  '|',
  'emotion',
  'insertLink',
  'uploadVideo',
  'uploadImage',
  'uploadAudio',
  'insertTable',
  'codeBlock',
  'divider',
  '|',
  'undo',
  'redo',
  '|',
  'fullScreen',
  'clearContent',
  'preview',
];
