/*[
  'bold',
  'underline',
  'italic',
  'through',
  'code',
  'sub',
  'sup',
  'clearStyle',
  'color',
  'bgColor',
  'fontSize',
  'fontFamily',
  'indent',
  'delIndent',
  'justifyLeft',
  'justifyRight',
  'justifyCenter',
  'justifyJustify',
  'lineHeight',
  'insertImage',
  'deleteImage',
  'editImage',
  'viewImageLink',
  'imageWidth30',
  'imageWidth50',
  'imageWidth100',
  'divider',
  'emotion',
  'insertLink',
  'editLink',
  'unLink',
  'viewLink',
  'codeBlock',
  'blockquote',
  'headerSelect',
  'header1',
  'header2',
  'header3',
  'header4',
  'header5',
  'todo',
  'redo',
  'undo',
  'fullScreen',
  'enter',
  'bulletedList',
  'numberedList',
  'insertTable',
  'deleteTable',
  'insertTableRow',
  'deleteTableRow',
  'insertTableCol',
  'deleteTableCol',
  'tableHeader',
  'tableFullWidth',
  'insertVideo',
  'uploadVideo',
  'editVideoSize',
  'uploadImage',
  'codeSelectLang',
  'clearContent',
  'preview',
  'replaceImage',
];*/

import { svgAlign, svgIndent, svgMore } from '../constants';

export default [
  'headerSelect',
  '|',
  'bold',
  'underline',
  'italic',
  {
    key: 'group-more-style',
    title: '更多',
    iconSvg: svgMore,
    menuKeys: ['through', 'sup', 'sub', 'clearStyle'],
  },
  'color',
  'bgColor',
  '|',
  {
    key: 'group-aligns',
    title: '对齐方式',
    iconSvg: svgAlign,
    menuKeys: ['justifyLeft', 'justifyCenter', 'justifyRight'],
  },
  {
    key: 'group-indent',
    title: '缩进方式',
    iconSvg: svgIndent,
    menuKeys: ['indent', 'delIndent'],
  },
  '|',
  'uploadImage',
  '|',
  'undo',
  'redo',
  '|',
  'fullScreen',
];
